<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CRUD</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b0b8093b-8fc9-4965-ab77-e309e6182585</testSuiteGuid>
   <testCaseLink>
      <guid>6ae0294b-7941-4bfd-8e40-44e12dba3c19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEST CASE PROJECT_01/CRUD PIM/ADD EMPLOYEE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26baa8de-530e-4e15-9365-0adac4c3e6bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74c76ad5-66d1-48e0-ab5b-3845357bda7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ce99a54-63ed-4b10-baa7-c4926e0e9bec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEST CASE PROJECT_01/CRUD PIM/EDIT EMPLOYEE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b1c04af-0130-45f7-b710-316c0b253306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fd4e816-d8bd-4d07-861e-1cea3e617920</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cfe2773-6086-4438-ad7d-66993062c2bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEST CASE PROJECT_01/CRUD PIM/DELETE EMPLOYEE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa640445-a51b-425f-a6b9-d7c576f4123e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a1e23ed-bd07-41e4-88eb-2cc39bf5b2d6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
