<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LOGIN AND LOGOUT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c9383db9-0982-4316-850d-53acc9b897c3</testSuiteGuid>
   <testCaseLink>
      <guid>4e7d4191-c358-46c3-96a4-aac8f178c77a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEST CASE PROJECT_01/LOGIN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac88973f-9bac-4871-9f63-7d62eacdfc93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>195b6d57-5386-4a0d-8038-e7f6e8ae7059</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4f3998a-0c76-4fdd-8964-7ef988f6514e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7efd59f7-3940-4f65-9e7c-07d8d61a7cf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb94555f-6b39-4c85-a011-ff62850aceeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TEST CASE PROJECT_01/LOGOUT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a7e763f-0e20-4f1f-b99f-e4fca30aaabd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d34dce-eb25-47d6-9097-e94ed64ab7fb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
